/**
 * keys.ts
 * Vapor PWA - Ed25519 Key Derivation for libp2p
 *
 * Derives Ed25519 keys from BIP-39 mnemonic for libp2p peer identity.
 * Uses a different HKDF domain than Vapor's X25519 keys to ensure separation.
 *
 * Key Architecture:
 * - Ed25519: Used for libp2p peer ID (signing, identity)
 * - X25519: Used for Vapor encryption (key exchange)
 * Both derived from the same mnemonic with different domain separators.
 */

import { KEY_DOMAINS } from './config';

const PBKDF2_ITERATIONS = 100000;

export interface Ed25519Keys {
  publicKey: Uint8Array;   // 32 bytes Ed25519 public key
  privateKey: Uint8Array;  // 32 bytes Ed25519 seed (private key)
}

/**
 * Derive Ed25519 keys from mnemonic for libp2p identity
 * Uses PBKDF2 → HKDF → Ed25519 seed derivation
 */
export async function deriveEd25519KeyFromMnemonic(mnemonic: string): Promise<Ed25519Keys> {
  const normalizedMnemonic = mnemonic.trim().toLowerCase();

  // BIP-39 style: mnemonic + "mnemonic" salt
  const mnemonicBytes = new TextEncoder().encode(normalizedMnemonic);
  const saltBytes = new TextEncoder().encode('mnemonic');

  // Import mnemonic as key material for PBKDF2
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    mnemonicBytes,
    'PBKDF2',
    false,
    ['deriveBits']
  );

  // Derive 64 bytes of seed material using PBKDF2
  const seedBits = await crypto.subtle.deriveBits(
    {
      name: 'PBKDF2',
      salt: saltBytes,
      iterations: PBKDF2_ITERATIONS,
      hash: 'SHA-512',
    },
    keyMaterial,
    512 // 64 bytes
  );

  const masterSeed = new Uint8Array(seedBits);

  // Use HKDF to derive 32 bytes for the Ed25519 seed
  // Uses different domain separator than X25519 to ensure key separation
  const hkdfKey = await crypto.subtle.importKey(
    'raw',
    masterSeed,
    'HKDF',
    false,
    ['deriveBits']
  );

  const privateKeyBits = await crypto.subtle.deriveBits(
    {
      name: 'HKDF',
      hash: 'SHA-256',
      salt: new TextEncoder().encode(KEY_DOMAINS.LIBP2P_IDENTITY),
      info: new TextEncoder().encode('ed25519-libp2p-key'),
    },
    hkdfKey,
    256 // 32 bytes
  );

  const seed = new Uint8Array(privateKeyBits);

  // Derive Ed25519 public key from seed using Web Crypto
  // Note: Web Crypto doesn't expose Ed25519 directly, so we use a derivation approach
  const publicKey = await deriveEd25519PublicKey(seed);

  return {
    publicKey,
    privateKey: seed,
  };
}

/**
 * Derive Ed25519 public key from seed
 * Uses a deterministic derivation since Web Crypto doesn't support Ed25519 directly
 */
async function deriveEd25519PublicKey(seed: Uint8Array): Promise<Uint8Array> {
  // For proper Ed25519, we need to use a library
  // libp2p/crypto handles this internally, so we'll derive a placeholder
  // that will be replaced when the actual keypair is generated by libp2p

  // Hash the seed to get a deterministic 32-byte value for the public key derivation
  // This is a simplified approach - the actual public key will be computed by @libp2p/crypto
  const hash = await crypto.subtle.digest('SHA-512', seed);
  const hashArray = new Uint8Array(hash);

  // Ed25519 public key derivation requires proper curve operations
  // We return the first 32 bytes as a placeholder
  // The actual public key will be derived when creating the peer ID
  return hashArray.slice(0, 32);
}

/**
 * Convert Ed25519 keys to libp2p-compatible format
 * This prepares the keys for use with @libp2p/peer-id-factory
 */
export function toLibp2pKeyFormat(keys: Ed25519Keys): {
  type: 'Ed25519';
  seed: Uint8Array;
} {
  return {
    type: 'Ed25519',
    seed: keys.privateKey,
  };
}

/**
 * Get the peer ID string from Ed25519 public key
 * This is a deterministic derivation for preview purposes
 * The actual peer ID will be computed by libp2p
 */
export async function getPeerIdPreview(publicKey: Uint8Array): Promise<string> {
  // Peer IDs are multihash of the public key
  // For Ed25519, the public key is embedded directly (identity multihash)
  // Format: <identity-multihash-code><length><public-key>

  // Identity multihash: 0x00 (code) + length + data
  // For display, we'll show a truncated base58 representation
  const hash = await crypto.subtle.digest('SHA-256', publicKey);
  const hashArray = new Uint8Array(hash);

  // Return first 8 bytes as hex for preview
  return '12D3KooW' + Array.from(hashArray.slice(0, 8))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');
}

/**
 * Securely wipe key material from memory
 */
export function wipeEd25519Keys(keys: Ed25519Keys): void {
  keys.privateKey.fill(0);
  keys.publicKey.fill(0);
}
